Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -79,12 +79,20 @@ jobs:
       - name: Extract vermagic
         run: |
           if [ -f "kmod-metadata/Packages" ]; then
+            echo "Packages file found!"
             vermagic=$(grep -oP 'vermagic="\K.*"' kmod-metadata/Packages)
-            echo "::set-output name=vermagic::$vermagic"
+            if [ $? -eq 0 ]; then
+              echo "::set-output name=vermagic::$vermagic"
+            else
+              echo "Error: Failed to extract vermagic value."
+              exit 1
+            fi
           else
             echo "Error: Packages file not found."
             exit 1
           fi
+        shell: /usr/bin/bash -e {0}
+
 
       - name: Modify kernel source vermagic
         run: |
